# Generated by Django 4.2.21 on 2025-06-04 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_category_options_alter_collection_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID категории'),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(max_length=100, verbose_name='Название категории'),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.category', verbose_name='Родительская категория'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='collection_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID коллекции'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='collection_name',
            field=models.CharField(max_length=100, verbose_name='Название коллекции'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user', verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='content',
            name='actor',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Актёр'),
        ),
        migrations.AlterField(
            model_name='content',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='content',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.collection', verbose_name='Коллекция'),
        ),
        migrations.AlterField(
            model_name='content',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='content',
            name='content_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID контента'),
        ),
        migrations.AlterField(
            model_name='content',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='content',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='content',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='content',
            name='director',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Режиссёр'),
        ),
        migrations.AlterField(
            model_name='content',
            name='genre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.genre', verbose_name='Жанр'),
        ),
        migrations.AlterField(
            model_name='content',
            name='progress',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Прогресс'),
        ),
        migrations.AlterField(
            model_name='content',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Оценка'),
        ),
        migrations.AlterField(
            model_name='content',
            name='release_year',
            field=models.IntegerField(verbose_name='Год выпуска'),
        ),
        migrations.AlterField(
            model_name='content',
            name='status',
            field=models.CharField(choices=[('watching', 'Смотрю'), ('planned', 'Запланировано'), ('completed', 'Просмотрено'), ('paused', 'На паузе')], max_length=50, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='content',
            name='type',
            field=models.CharField(choices=[('movie', 'Фильм'), ('series', 'Сериал')], max_length=20, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='content',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='content',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user', verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='genre_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID жанра'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='genre_name',
            field=models.CharField(max_length=100, verbose_name='Название жанра'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Электронная почта'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password_hash',
            field=models.CharField(max_length=255, verbose_name='Хэш пароля'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID пользователя'),
        ),
    ]
