# Generated by Django 4.2.22 on 2025-06-10 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_user_password_hash_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='content_posters/', verbose_name='Постер'),
        ),
    ]
