# Generated by Django 4.2.22 on 2025-06-11 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_content_progress_remove_content_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='user',
        ),
    ]
