# Generated by Django 4.2.22 on 2025-06-14 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_content_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='status',
            field=models.CharField(choices=[('watching', 'Смотрю'), ('planned', 'Запланировано'), ('completed', 'Просмотрено'), ('paused', 'На паузе'), ('dropped', 'Брошено')], max_length=50, verbose_name='Статус'),
        ),
    ]
