# Generated by Django 4.2.22 on 2025-06-17 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_collection_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='status',
            field=models.CharField(choices=[('completed', 'Просмотрено'), ('watching', 'Смотрю'), ('planned', 'Запланировано'), ('paused', 'На паузе'), ('dropped', 'Брошено')], default='completed', max_length=50, verbose_name='Статус'),
        ),
    ]
