# Generated by Django 4.2.22 on 2025-06-17 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_collection_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='category',
        ),
        migrations.AlterField(
            model_name='content',
            name='genre',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Жанр'),
        ),
    ]
