# Generated by Django 4.2.22 on 2025-06-17 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_content_category_alter_content_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='tmdb_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='TMDB ID'),
        ),
        migrations.AddField(
            model_name='content',
            name='tmdb_type',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='TMDB тип (movie/tv)'),
        ),
    ]
